#include "test.h"

void test_membership(void)
{
    BspForest forest = {0};
    BspTree *tree, *other, *mask;
    BspNode *root, *one, *two, *branch;
    uint64_t ids[] = {1, 2, 3}, reordered[] = {3, 1, 2};
    uint64_t bad[] = {1, 1}, zero[] = {1, 0}, generation, one_id, two_id;
    BspRect bounds = {7, -11, 1200, 800};
    CHECK(!bsp_workspace(&forest, -1, 1, 1));
    CHECK(!bsp_workspace(&forest, 0, 0, 1));
    CHECK(!bsp_workspace(&forest, 0, 1, 0));
    CHECK(!bsp_workspace(NULL, 0, 1, 1));
    tree = test_view(&forest, 0, 1);
    CHECK(bsp_workspace(&forest, 0, 1, 0)->tree.generation == tree->generation);
    CHECK(bsp_tree_sync(tree, ids, 2, 0, bounds));
    root = tree->root;
    one = bsp_find(tree, 1);
    two = bsp_find(tree, 2);
    one_id = one->id;
    two_id = two->id;
    CHECK(root->axis == BSP_HORIZONTAL && root->child[0] == one && root->child[1] == two);
    CHECK(bsp_tree_sync(tree, ids, 3, 2, bounds));
    branch = two->parent;
    CHECK(branch->axis == BSP_VERTICAL && branch->child[0] == two);
    CHECK(branch->child[1]->window == 3 && one->id == one_id && two->id == two_id);
    CHECK(bsp_tree_adjust(tree, 2, BSP_VERTICAL, 0.15));
    generation = tree->generation;
    CHECK(bsp_tree_sync(tree, reordered, 3, 0, bounds));
    CHECK(tree->root == root && two->parent == branch && branch->ratio == 0.65);
    CHECK(tree->generation == generation);
    CHECK(!bsp_tree_sync(tree, bad, 2, 0, bounds));
    CHECK(!bsp_tree_sync(tree, zero, 2, 0, bounds));
    CHECK(!bsp_tree_sync(tree, NULL, 1, 0, bounds));
    CHECK(!bsp_tree_sync(tree, ids, SIZE_MAX, 0, bounds));
    CHECK(tree->generation == generation);
    test_tree(tree, 3);
    CHECK(bsp_tree_sync(tree, ids + 1, 2, 0, bounds));
    CHECK(tree->root == branch && !branch->parent && branch->ratio == 0.65);
    CHECK(!bsp_find(tree, 1) && bsp_find(tree, 2) == two);
    CHECK(tree->generation != generation);
    CHECK(bsp_tree_sync(tree, ids + 1, 1, 0, bounds));
    CHECK(tree->root == two && !two->parent && two->id == two_id);
    test_tree(tree, 1);
    generation = tree->generation;
    CHECK(bsp_tree_sync(tree, NULL, 0, 0, bounds));
    CHECK(tree->generation != generation);
    generation = tree->generation;
    CHECK(bsp_tree_sync(tree, ids, 1, 0, bounds));
    CHECK(tree->generation != generation && tree->root->id > two_id);
    other = test_view(&forest, 1, 1);
    mask = test_view(&forest, 0, 3);
    CHECK(bsp_tree_sync(other, ids, 3, 0, bounds));
    CHECK(bsp_tree_sync(mask, ids, 2, 0, bounds));
    CHECK(bsp_tree_swap(other, 1, 3));
    CHECK(tree->root->window == 1 && bsp_find(mask, 1)->id != 0);
    bsp_forget_window(&forest, 1);
    test_tree(tree, 0);
    test_tree(other, 2);
    test_tree(mask, 1);
    CHECK(!bsp_find(other, 1) && !bsp_find(mask, 1));
    generation = mask->generation;
    bsp_forget_monitor(&forest, 0);
    CHECK(!bsp_workspace(&forest, 0, 1, 0) && !bsp_workspace(&forest, 0, 3, 0));
    CHECK(bsp_workspace(&forest, 1, 1, 0));
    mask = test_view(&forest, 0, 3);
    CHECK(mask->generation != generation);
    bsp_forest_clear(&forest);
    CHECK(!forest.views);
    bsp_forest_clear(&forest);
    bsp_forest_clear(NULL);
    bsp_forget_window(NULL, 1);
    bsp_forget_monitor(NULL, 1);
}
